version: '3.8'
services:
  app:
    container_name: website
    image: hermann-gmeiner
    build:
      network: host
      context: ./
      target: builder
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - images:/app/public/articles/images:ro  # add this line
    ports:
      - "3000:3000"
      - "4983:4983"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:adminadmin@db:5432/db
      AUTH_SECRET: BWuyOm5juK6o2fq1QW00lTplaKFdgpBBnMwb1SLDDEk=
      ARTICLE_PATH: /app/static-files/articles
      PHOTO_PATH: /app/static-files/photos

  db:
    image: postgres:13-alpine
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - db-data:/var/lib/postgresql/data

  static:
    container_name: static-files
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static-files:/usr/share/nginx/html
    ports:
      - "8080:8080"
volumes:
  db-data:
  images:


