import type { ReactNode } from "react";
//
import type { Metadata } from "next";
//
import ThemeProvider from "@/components/layout/ThemeProvider";
//
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import cn from "@/lib/cn";
import { Toaster } from "@/components/general/Sonner";

export const metadata: Metadata = {
  title: "Shkolla 'Hermann Gmeiner'",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={"h-screen w-screen"}>
      <body
        className={cn(
          "relative h-full w-full bg-background text-foreground",
          GeistSans.className
        )}
      >
        <ThemeProvider attribute={"class"} defaultTheme={"dark"} enableSystem>
          <Navbar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
