//
import type { Metadata } from "next";
//
import ThemeProvider from "@/components/layout/ThemeProvider";
//
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { Navbar } from "@/components/home/Navbar";
import cn from "@/lib/cn";
import { Toaster } from "@/components/general/Sonner";
import type { LayoutProps } from "@/types/navigation/LayoutProps";

export const metadata: Metadata = {
  title: "Shkolla 'Hermann Gmeiner'",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" className={"h-screen w-screen overflow-hidden"}>
      <body
        className={cn(
          "relative size-full max-h-full max-w-full overflow-hidden bg-background text-foreground",
          GeistSans.className
        )}
      >
        <ThemeProvider attribute={"class"} defaultTheme={"dark"} enableSystem>
          <Navbar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
