import type { ReactNode } from "react";
//
import type { Metadata } from "next";
//
import ThemeProvider from "@/components/layout/ThemeProvider";
//
import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shkolla 'Hermann Gmeiner'",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ThemeProvider attribute={"class"} defaultTheme={"dark"} enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
